### ISSUE TITLE
Blank `template:` option does not disable comments

### ISSUE THREAD

**Issue by xcskier56** [Namchee/conventional-pr#56]
I have tried both `template: ` and `template: ""` and both are still leaving a comment in the PR. Here's my full action yaml file:

```yaml
name: Check PR title
on:
  pull_request:

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - name: Validates the pull request
        uses: Namchee/conventional-pr@v0.7.2
        with:
          access_token: ${{ secrets.GH_TOKEN}}
          close: false
          title_pattern: <my-custom-regex>
          issue: false
          template: ""
          label:
```
