### ISSUE TITLE
feat: jira issue key

### ISSUE THREAD

**Issue by juliankasimir** [Namchee/conventional-pr#89]
We use [jira-prepare-commit-msg](https://www.npmjs.com/package/jira-prepare-commit-msg) with [Husky](https://typicode.github.io/husky/) and thus automatically add the Jira issue ID to the git commit. The whole thing is checked in advance for [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/).

However, the hook then fails, so I made a small adjustment as a pattern regex:

Default:
`title_pattern: '([\w\-]+)(\([\w\-]+\))?!?: [\w\s:\-]+'`

with Jira issue key `(\[([A-Z]+\-\d+)\] )?`

Default Regex + Jira Issue Key:
`title_pattern: '([\w\-]+)(\([\w\-]+\))?!?: (\[([A-Z]+\-\d+)\] )?[\w\ s:\-]+'`

Is there an easier way without regex?

```
      - name: '✅ Lint PR'
        uses: Namchee/conventional-pr@v0.13.0
        with:
          ...
          title_pattern: '([\w\-]+)(\([\w\-]+\))?!?: (\[([A-Z]+\-\d+)\] )?[\w\s:\-]+' # with Jira issue key (\[([A-Z]+\-\d+)\] )?
          message: |
            This Pull Request doesn't follow the [conventional commits pattern](https://www.conventionalcommits.org/en/v1.0.0/)
```
